services:
  app:
    image: node:18-alpine
    container_name: react_04
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app/:/app
    # command: sh -c "yarn create next-app . && yarn install && yarn run dev"
    # command: sh -c "yarn install && yarn start"
    command: sh -c "yarn run dev"
    # command: sh -c "tail -f /dev/null"